name: Build and deploy Python app to Azure Web App - AZURETOXICITYDEMO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_33327CFA446149A8B8C5CFBCDA7E0170 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A0B9B7674D34000988E9419D40A1302 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CDD1D144A71F4598964FCCD6E9AA8ACA }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AZURETOXICITYDEMO'
          slot-name: 'Production'
          package: .