name: Build and deploy Python app to Azure Web App - AZURETOXICITYDEMO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Create deployment package
        run: |
          # Copy app files to root
          cp app/main.py .
          cp -r app/templates .
          ls -la
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            main.py
            templates/
            requirements.txt
            startup.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./deploy
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_33327CFA446149A8B8C5CFBCDA7E0170 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A0B9B7674D34000988E9419D40A1302 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CDD1D144A71F4598964FCCD6E9AA8ACA }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AZURETOXICITYDEMO'
          slot-name: 'Production'
          package: ./deploy